services:
  frontend_dev:
    image: frontend_dev
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8081
      - REACT_APP_WS_URL=ws://localhost:8081
    depends_on:
      - backend_dev

  backend_dev:
    image: backend_dev
    restart: always
    working_dir: /app
    ports:
      - "8081:8081"
    command: sh -c "npm install && npm run start"
    environment:
      - PORT=8081
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=MEAL_ORDER
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .dev.env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MEAL_ORDER
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: