services:
  mysql:
    image: meal-order-mysql:latest
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    # volumes: 
    #   - mysql-data:/var/lib/mysql
    networks:
      - backend-net
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:3306"]
        interval: 30s
        timeout: 10s
        retries: 5

  backend:
    image: meal-order-backend:latest
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-net
    ports:
      - 127.0.0.1:8081:8081
    env_file:
      - meal_order_backend.env # The variables match those in backend/.env, except for one difference: "DB_HOST=mysql"
  
  frontend:
    image: meal-order-frontend:latest
    restart: always
    ports:
      - 127.0.0.1:3000:3000

networks:
  backend-net:
    driver: bridge

# volumes:
#   mysql-data:
#     driver: local