apiVersion: apps/v1
kind: Deployment
metadata:
  name: meal-order-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meal-order-backend
  template:
    metadata:
      labels:
        app: meal-order-backend
    spec:
      containers:
      - name: meal-order-backend
        image: mealorderimages.azurecr.io/meal-order-backend:latest
        # resources:
        #   limits:
        #     memory: "356Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_DATABASE
        - name: MAIL_USER
          valueFrom:
            configMapKeyRef:
              name: mail-config
              key: MAIL_USER
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: MAIL_PASSWORD
        - name: AZURE_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: blob-config
              key: AZURE_ACCOUNT
        - name: AZURE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: blob-secret
              key: AZURE_CONNECTIONSTRING
        - name: AZURE_KEY
          valueFrom:
            secretKeyRef:
              name: blob-secret
              key: AZURE_KEY
        - name: AZURE_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: blob-config
              key: AZURE_CONTAINER


---

apiVersion: v1
kind: Service
metadata:
  name: meal-order-backend-service
spec:
  type: LoadBalancer
  selector:
    app: meal-order-backend
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP