# configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PORT: "8081"
  # REACT_APP_BACKEND_HOST: "http://meal-order-backend-service"
  REACT_APP_BACKEND_HOST: "http://20.27.91.154"
  REACT_APP_WS_HOST: "ws://20.27.91.154"
  # REACT_APP_WS_PORT: "8081"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "mealorder26.mysql.database.azure.com"
  DB_PORT: "3306"
  DB_USER: "mealorder26"
  DB_DATABASE: "MEAL_ORDER"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-config
data:
  MAIL_USER: "r11922103@csie.ntu.edu.tw"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blob-config
data:
  AZURE_ACCOUNT: "allen23648858gmail.com"
  AZURE_CONTAINER: image